// @ts-nocheck
import { ChevronRight } from "lucide-react";
import { C } from "@/lib/theme";
import { f } from "@/lib/format";
import { Tag } from "./Tag";

const BRAND_IMG={"Flipkart":"/brands/flipkart.png","Amazon":"/brands/amazon.png","Swiggy":"/brands/swiggy.png","Zomato":"/brands/zomato.png","BigBasket":"/brands/bb.png","Myntra":"/brands/myntra.png","Adidas":"/brands/adiddas.png","MuscleBlaze":"/brands/muscle-blaze.png"};

export function TxnRow({t,onTap}){const brandImg=BRAND_IMG[t.brand];return(<div onClick={onTap} style={{padding:"22px 0",borderBottom:`1px solid ${C.brd}`,cursor:"pointer"}}><div style={{display:"flex",alignItems:"flex-start",gap:16}}><div style={{width:38,height:39,borderRadius:4,border:"1px solid #EDEDED",background:"#fff",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0,overflow:"hidden"}}>{brandImg?<img src={brandImg} alt="" style={{width:36,height:31,objectFit:"contain"}}/>:<span style={{fontSize:16}}>{t.icon}</span>}</div><div style={{flex:1}}><div style={{display:"flex",justifyContent:"space-between"}}><div><div style={{display:"flex",alignItems:"center",gap:6}}><span style={{fontSize:14,fontWeight:600,color:C.text}}>{t.brand} · ₹{f(t.amt)}</span>{t.manuallyTagged&&<span style={{fontSize:10,fontWeight:600,color:C.blue,background:C.blueBg,padding:"2px 6px",borderRadius:4}}>Tagged</span>}</div><div style={{fontSize:11,color:C.dim,marginTop:3}}>{t.date} | {t.via}</div></div><div style={{display:"flex",gap:10,flexShrink:0}}>{t.saved!==null&&<div style={{textAlign:"right"}}><div style={{fontSize:14,fontWeight:700,color:C.text}}>₹{f(t.saved)}</div><div style={{fontSize:10,color:C.dim}}>Saved</div></div>}{t.saved===null&&<div style={{textAlign:"right"}}><div style={{fontSize:14,fontWeight:700,color:C.dim}}>—</div><div style={{fontSize:10,color:C.dim}}>Earned</div></div>}{t.missed>0&&<div style={{textAlign:"right"}}><div style={{fontSize:14,fontWeight:700,color:C.orange}}>₹{f(t.missed)}</div><div style={{fontSize:10,color:C.orange}}>Missed</div></div>}</div></div><div style={{display:"flex",alignItems:"center",justifyContent:"space-between"}}><Tag text={t.tag} color={t.tagColor} bg={t.tagBg}/><div style={{width:28,height:28,borderRadius:8,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><ChevronRight size={14} strokeWidth={1.5} color={C.dim}/></div></div></div></div></div>);}
