// LEGACY SCREEN: kept for fallback/reference only.
// Active implementation now routes through `src/features/new/HomeScreen.tsx`.
// @ts-nocheck
import { CreditCard, ChevronRight, HelpCircle, Mail, Smartphone } from "lucide-react";
import { C, FN } from "@/lib/theme";
import { f } from "@/lib/format";
import { FL } from "@/components/shared/FontLoader";
import { SemiGauge, DotDiv, ThkDiv } from "@/components/shared/Primitives";
import { TxnRow } from "@/components/shared/TxnRow";
import { ActionCard } from "@/components/shared/ActionCard";
import { Circles } from "@/components/shared/Circles";
import { SortFilter, doSort, doFilter } from "@/components/shared/SortFilter";
import { CARDS, SEMI_CARDS } from "@/data/cards";
import { ACTIONS } from "@/data/actions";
import { ALL_TXNS } from "@/data/transactions";
import { SPEND_CATS, SPEND_BRANDS, TOTAL_ACC } from "@/data/spend";
import { useAppContext } from "@/store/AppContext";
import { NavBar as NavBarShared } from "@/components/shared/NavBar";
import { Toast, InfoBS, TxnSheet, ActSheet, GmailNudgeBanner, GmailNudgePopup, GmailNudgeSheet, RetroOverlay, VoiceFlowOverlay, CatBS, FilterSheet } from "@/components/sheets/BottomSheets";

export function HomeScreen(){
  const ctx:any = useAppContext();
  const {
    setScreen, openCard, isState1, isState2, isState3,
    getCardDisplayName, isCardMapped, hasGmail,
    setShowGmailNudgeSheet, setInfoSheet, setActSheet, setTxnSheet, setCatSheet,
    setRedeemCard, setRedeemPts, setRedeemResult, setRedeemPref,
    setSelBrand, setCalcAmt, setCalcResult, setSearchQ,
    getFilteredActions, sortBy, setSortBy, filters, toggleFilter, setFilterSheet,
    spendTab, setSpendTab, showAllBrands, setShowAllBrands,
    activeTxnList, filtered, goTxns
  } = ctx;
  const NavBar = NavBarShared;

  const homeTxns=filtered.slice(0,5);const spendDataFull=spendTab==="Categories"?SPEND_CATS:SPEND_BRANDS;const spendData=spendTab==="Brands"&&!showAllBrands?spendDataFull.slice(0,10):spendDataFull;const maxAmt=Math.max(...spendData.map((d:any)=>d.amt));
  return(<div style={{fontFamily:FN,maxWidth:400,margin:"0 auto",height:"100vh",display:"flex",flexDirection:"column",position:"relative"}}><div data-scroll="1" style={{flex:1,overflowY:"auto",WebkitOverflowScrolling:"touch",background:C.bg,paddingBottom:100}}><div className="slide-in"><FL/>
  <div style={{background:"linear-gradient(180deg,#1a3fc7 0%,#2563eb 40%,#3b82f6 100%)",padding:"56px 24px 36px",color:"#fff"}}>
  <div style={{display:"flex",justifyContent:"space-between",marginBottom:22}}><span style={{fontSize:10,fontWeight:700,opacity:0.5,letterSpacing:1.5,textTransform:"uppercase"}}>Your cards</span><span onClick={()=>openCard(0)} style={{fontSize:11,fontWeight:600,opacity:0.7,cursor:"pointer"}}>View All &gt;</span></div>
  <div style={{display:"flex",gap:10,marginBottom:isState1?18:28}}>{CARDS.map((card:any,i:number)=>{const mapped=isCardMapped(i);const label=isState3?card.name.split(" ").pop():isState2?getCardDisplayName(i).split(" ").slice(-1)[0]:"••"+SEMI_CARDS[i].last4;return(<div key={i} onClick={()=>openCard(i)} style={{display:"flex",flexDirection:"column",alignItems:"center",gap:6,cursor:"pointer",position:"relative"}}><div style={{width:72,height:46,borderRadius:8,background:`linear-gradient(135deg,${card.color},${card.accent})`,border:"1px solid rgba(255,255,255,0.15)",display:"flex",alignItems:"center",justifyContent:"center",boxShadow:"0 4px 20px rgba(0,0,0,0.08)"}}><CreditCard size={18} strokeWidth={1.5} color="rgba(255,255,255,0.7)"/></div><span style={{fontSize:10,fontWeight:600,color:"rgba(255,255,255,0.6)"}}>{label}</span>{isState1&&<span onClick={(e)=>{e.stopPropagation();setShowGmailNudgeSheet(true);}} style={{marginTop:2,fontSize:10,fontWeight:700,color:C.orange,background:C.orangeBg,padding:"2px 6px",borderRadius:3,cursor:"pointer"}}>PARTIAL</span>}</div>);})}<div onClick={()=>setInfoSheet({title:"Add a Card",desc:"This feature will let you add more credit cards to your wallet for analysis. Coming soon!"})} style={{display:"flex",flexDirection:"column",alignItems:"center",gap:6}}><div style={{width:46,height:46,borderRadius:8,background:"rgba(255,255,255,0.1)",border:"1px dashed rgba(255,255,255,0.3)",display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer"}}><span style={{fontSize:20,color:"rgba(255,255,255,0.4)"}}>+</span></div></div></div>
  {!isState1&&<>
  <div style={{textAlign:"center",fontSize:18,fontWeight:700,lineHeight:1.45,marginBottom:12}}>You are saving<br/>70% less than what you could save</div>
  <div style={{display:"flex",justifyContent:"center",position:"relative",margin:"0 0 -20px"}}><SemiGauge pct={30}/><div style={{position:"absolute",bottom:10,left:"50%",transform:"translateX(-50%)",textAlign:"center"}}><div style={{fontSize:32,fontWeight:700}}>30%</div><div style={{fontSize:10,fontWeight:600,color:"rgba(255,255,255,0.4)",letterSpacing:1}}>Saving efficiency</div></div></div>
  <div style={{display:"flex",padding:"14px 4px",borderRadius:14,background:"rgba(255,255,255,0.08)",backdropFilter:"blur(12px)",border:"1px solid rgba(255,255,255,0.18)",marginTop:28}}><div style={{flex:1,textAlign:"center",borderRight:"1px solid rgba(255,255,255,0.12)"}}><div style={{fontSize:11,color:"rgba(255,255,255,0.55)",fontWeight:600}}>You saved</div><div style={{fontSize:16,fontWeight:700,marginTop:4}}>₹50,000</div></div><div style={{flex:1,textAlign:"center"}}><div style={{fontSize:11,color:"rgba(255,255,255,0.55)",fontWeight:600}}>You could save</div><div style={{fontSize:16,fontWeight:700,marginTop:4}}>₹1,50,000</div></div></div>
  <div onClick={()=>setScreen("optimize")} style={{marginTop:20,padding:"18px 22px",borderRadius:16,background:"#111827",display:"flex",alignItems:"center",justifyContent:"center",gap:8,cursor:"pointer",boxShadow:"0 4px 20px rgba(0,0,0,0.2)"}}><span style={{fontSize:14,fontWeight:700,color:"#fff"}}>See how you can improve</span><ChevronRight size={16} strokeWidth={2} color="rgba(255,255,255,0.6)"/></div>
  </>}
  </div>
  <div style={{padding:"0 24px 44px"}}>
  <DotDiv label="Actions to consider (10)"/>
  {!hasGmail&&<div style={{marginBottom:14}}><GmailNudgeBanner line="Unlock all your action items" subline="Connect Gmail for milestone tracking, fee waivers and vouchers" onPress={()=>setShowGmailNudgeSheet(true)}/></div>}
  <div style={{display:"flex",flexDirection:"column",gap:16}}>{getFilteredActions(ACTIONS).map((a:any,i:number)=>(<div key={i} style={i===0?{background:"linear-gradient(135deg,#fffbeb,#fef3c7)",borderRadius:16,padding:1}:{}}><ActionCard a={a} onTap={()=>setActSheet(a)} onCta={()=>{if(a.type==="points"){setRedeemCard(null);setRedeemPts("");setRedeemResult(null);setRedeemPref(null);setScreen("redeem");}else if(a.type==="benefit"){setRedeemCard(null);setRedeemPts("");setRedeemResult(null);setRedeemPref(null);setScreen("redeem");}else if(a.type==="fee"){openCard(2);}}}/></div>))}</div>
  <div style={{display:"flex",justifyContent:"center",padding:"14px 0"}}><div onClick={()=>setScreen("actions")} style={{padding:"10px 28px",borderRadius:12,background:C.white,border:`1px solid ${C.brd}`,fontSize:12,fontWeight:600,color:C.text,boxShadow:"0 1px 4px rgba(0,0,0,0.04)",cursor:"pointer"}}>View all (7 more) ▾</div></div>
  <DotDiv label="Tools to explore"/>
  <div style={{display:"flex",gap:14}}>{[
    {label:"Redemption\nFinder",hue:"linear-gradient(145deg,#4f46e5,#818cf8)",stroke:"rgba(99,102,241,0.35)",shadow:"rgba(79,70,229,0.25)",act:()=>{setScreen("redeem");setRedeemCard(null);setRedeemPts("");setRedeemResult(null);setRedeemPref(null);},
      icon:(<div style={{width:52,height:52,borderRadius:14,background:"rgba(255,255,255,0.2)",border:"1px solid rgba(255,255,255,0.25)",display:"flex",alignItems:"center",justifyContent:"center",boxShadow:"0 4px 16px rgba(0,0,0,0.08)",position:"relative"}}><div style={{width:28,height:28,borderRadius:"50%",background:"linear-gradient(135deg,#fbbf24,#f59e0b)",boxShadow:"0 0 16px rgba(251,191,36,0.4)",display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:14,color:"#fff"}}>₹</span></div></div>)},
    {label:"Savings\nCalculator",hue:"linear-gradient(145deg,#1d4ed8,#60a5fa)",stroke:"rgba(29,78,216,0.35)",shadow:"rgba(29,78,216,0.25)",act:()=>{setScreen("calc");setSelBrand(null);setCalcAmt("");setCalcResult(null);setSearchQ("");},
      icon:(<div style={{width:44,height:52,borderRadius:12,background:"rgba(255,255,255,0.2)",border:"1px solid rgba(255,255,255,0.25)",display:"flex",flexDirection:"column",padding:"8px 7px",gap:4,boxShadow:"0 4px 16px rgba(0,0,0,0.08)"}}><div style={{height:12,borderRadius:4,background:"rgba(255,255,255,0.4)"}}/><div style={{flex:1,display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:3}}>{[0,1,2,3,4,5].map(d=>(<div key={d} style={{borderRadius:3,background:d===5?"#4ade80":"rgba(255,255,255,0.2)"}}/>))}</div></div>)},
    {label:"Best Cards\nfor you",hue:"linear-gradient(145deg,#0369a1,#38bdf8)",stroke:"rgba(3,105,161,0.35)",shadow:"rgba(3,105,161,0.25)",act:()=>setScreen("bestcards"),
      icon:(<div style={{position:"relative",width:52,height:48}}><div style={{position:"absolute",top:0,left:4,width:44,height:28,borderRadius:8,background:"rgba(255,255,255,0.18)",border:"1px solid rgba(255,255,255,0.15)",transform:"rotate(-3deg)"}}/><div style={{position:"absolute",bottom:0,left:4,width:44,height:28,borderRadius:8,background:"rgba(255,255,255,0.4)",border:"1px solid rgba(255,255,255,0.3)",boxShadow:"0 4px 12px rgba(0,0,0,0.08)",display:"flex",alignItems:"center",padding:"0 8px"}}><div style={{width:14,height:10,borderRadius:3,background:"#fbbf24"}}/></div></div>)}
  ].map((t,i)=>(<div key={i} onClick={t.act} style={{flex:1,display:"flex",flexDirection:"column",alignItems:"center",cursor:"pointer"}}><div style={{width:"100%",aspectRatio:"1",borderRadius:20,background:t.hue,border:`1.5px solid ${t.stroke}`,display:"flex",alignItems:"center",justifyContent:"center",boxShadow:`0 8px 24px ${t.shadow}`}}>{t.icon}</div><div style={{fontSize:12,fontWeight:600,color:C.text,textAlign:"center",lineHeight:1.4,whiteSpace:"pre-line",marginTop:10}}>{t.label}</div></div>))}</div>
  <ThkDiv/>
  <div style={{fontSize:22,fontWeight:700,color:C.text}}>Transaction Analysis</div>
  <div style={{fontSize:12,color:C.sub,marginTop:6}}>Showing report from Last 30 days</div>
  {!isState1&&<Circles/>}
  <div style={{fontSize:10,fontWeight:700,color:C.sub,letterSpacing:2,textTransform:"uppercase",textAlign:"center",margin:"16px 0 10px"}}>Transactions</div>
  <SortFilter sortBy={sortBy} setSortBy={setSortBy} filters={filters} toggleFilter={toggleFilter} onFilterOpen={()=>setFilterSheet(true)} customFilters={isState1?[{label:"Unaccounted",Ic:HelpCircle},{label:"HSBC ••7891",filterKey:"Travel One",Ic:CreditCard,color:"#0c2340"},{label:"Axis ••4521",filterKey:"Flipkart",Ic:CreditCard,color:"#5b2c8e"},{label:"HSBC ••3364",filterKey:"Live+",Ic:CreditCard,color:"#006d5b"},{label:"UPI",filterKey:"UPI",Ic:Smartphone,color:"#6d28d9"}]:null}/>
  <div>{homeTxns.map((t:any,i:number)=>{if(isState1){return(<div key={i} style={{padding:"16px 12px",margin:"0 -12px",borderBottom:`1px solid ${C.brd}`}}><div style={{display:"flex",alignItems:"center",gap:16}}><div style={{width:36,height:36,borderRadius:"50%",background:C.bg,display:"flex",alignItems:"center",justifyContent:"center",fontSize:16,flexShrink:0}}>{t.icon}</div><div style={{flex:1}}><div style={{fontSize:13,fontWeight:700,color:C.text}}>{t.brand} · ₹{f(t.amt)}</div><div style={{fontSize:10,color:C.dim,marginTop:2}}>{t.date} | {t.bank==="HSBC"?"HSBC ••"+(t.last4==="7891"?"7891":"3364"):t.bank==="Axis"?"Axis ••4521":t.via}</div></div></div></div>);}return(<TxnRow key={i} t={t} onTap={()=>{if(t.unaccounted)setCatSheet(t);else setTxnSheet(t);}}/>);})}</div>
  <div style={{display:"flex",justifyContent:"center",padding:"14px 0"}}><div onClick={()=>goTxns()} style={{padding:"10px 28px",borderRadius:12,background:C.white,border:`1px solid ${C.brd}`,fontSize:12,fontWeight:600,color:C.text,boxShadow:"0 1px 4px rgba(0,0,0,0.04)",cursor:"pointer"}}>View all ({filtered.length}) ▾</div></div>
  {isState1?<div onClick={()=>setShowGmailNudgeSheet(true)} style={{borderRadius:16,background:"linear-gradient(135deg,#eff6ff,#dbeafe)",border:"1px solid "+C.blueBrd,padding:"20px 18px",marginBottom:8,display:"flex",alignItems:"center",gap:14,cursor:"pointer",overflow:"hidden",position:"relative",boxShadow:"0 2px 8px rgba(29,78,216,0.06)"}}>
  <div style={{width:54,height:54,borderRadius:16,background:"linear-gradient(135deg,#bfdbfe,#93c5fd)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><Mail size={24} strokeWidth={1.5} color={C.blue}/></div>
  <div style={{flex:1,zIndex:1}}><div style={{fontSize:15,fontWeight:700,lineHeight:1.5,color:C.text}}>Unlock full card insights</div><div style={{fontSize:12,color:C.sub,marginTop:4,lineHeight:1.4}}>Identify exact cards, see benefits & fee waivers</div></div>
  <ChevronRight size={18} strokeWidth={1.5} color={C.sub}/>
</div>:<div onClick={()=>setScreen("bestcards")} style={{borderRadius:16,background:C.white,padding:"20px",marginBottom:8,display:"flex",alignItems:"center",gap:16,cursor:"pointer",boxShadow:"0 2px 16px rgba(0,0,0,0.04)"}}>
  <div style={{width:56,height:72,borderRadius:12,background:"linear-gradient(145deg,#1a1a2e,#2d3748)",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",boxShadow:"0 4px 16px rgba(0,0,0,0.2)",flexShrink:0}}><CreditCard size={20} strokeWidth={1.5} color="rgba(255,255,255,0.5)"/><div style={{fontSize:6,color:"rgba(255,255,255,0.4)",fontWeight:700,marginTop:4}}>INFINIA</div></div>
  <div style={{flex:1}}><div style={{fontSize:14,fontWeight:700,color:C.text,lineHeight:1.5}}>HDFC Infinia could save you ₹5,000 more per month</div><div style={{display:"inline-flex",marginTop:10,alignItems:"center",gap:4}}><span style={{fontSize:12,fontWeight:600,color:C.blue}}>See details</span><ChevronRight size={14} strokeWidth={1.5} color={C.blue}/></div></div>
</div>}
  <ThkDiv/>
  <div style={{fontSize:22,fontWeight:700,color:C.text}}>Spend Analysis</div>
  <div style={{fontSize:12,color:C.sub,marginTop:8,marginBottom:28}}>Based on your spends of Last 365 days</div>
  <div style={{display:"flex",borderRadius:10,background:C.white,border:`1px solid ${C.brd}`,padding:3,marginBottom:22}}>{["Categories","Brands"].map(t=>(<div key={t} onClick={()=>{setSpendTab(t);setShowAllBrands(false);}} style={{flex:1,textAlign:"center",padding:"10px 0",borderRadius:8,cursor:"pointer",background:spendTab===t?C.blue:"transparent",color:spendTab===t?"#fff":C.sub,fontSize:13,fontWeight:700}}>{t}</div>))}</div>
  <div style={{padding:20,borderRadius:16,background:C.blueBg,border:`1px solid ${C.blueBrd}`,textAlign:"center",marginBottom:28}}><div style={{fontSize:28,fontWeight:700,color:C.blue}}>₹{f(TOTAL_ACC)}</div><div style={{fontSize:12,color:C.sub,marginTop:6}}>Total Accounted Spends</div></div>
  <div style={{display:"flex",flexDirection:"column",gap:20}}>{spendData.map((item:any,i:number)=>(<div key={i} style={{display:"flex",alignItems:"center",gap:16}}><div style={{width:40,height:40,borderRadius:10,background:`${item.color}18`,border:`1px solid ${item.color}30`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:18,flexShrink:0}}>{item.Ic?<item.Ic size={18} strokeWidth={1.5} color={item.color||C.sub}/>:item.icon}</div><div style={{flex:1}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><span style={{fontSize:13,fontWeight:600,color:C.text}}>{item.name}<span style={{fontSize:10,fontWeight:400,color:C.dim,marginLeft:16}}>{item.txns} txns</span></span><span style={{fontSize:13,fontWeight:700,color:C.text}}>₹{f(item.amt)}</span></div><div style={{height:6,borderRadius:3,background:"#e5e7eb",overflow:"hidden"}}><div style={{height:"100%",width:`${(item.amt/maxAmt)*100}%`,borderRadius:3,background:`linear-gradient(90deg,${item.color},${item.color}88)`}}/></div></div></div>))}</div>
  {spendTab==="Brands"&&!showAllBrands&&<div style={{display:"flex",justifyContent:"center",padding:"16px 0"}}><div onClick={()=>setShowAllBrands(true)} style={{padding:"10px 28px",borderRadius:12,background:C.white,border:`1px solid ${C.brd}`,fontSize:12,fontWeight:600,color:C.text,boxShadow:"0 1px 4px rgba(0,0,0,0.04)",cursor:"pointer"}}>View all {SPEND_BRANDS.length} brands ▾</div></div>}
  {spendTab==="Brands"&&showAllBrands&&<div style={{display:"flex",justifyContent:"center",padding:"16px 0"}}><div onClick={()=>setShowAllBrands(false)} style={{padding:"10px 28px",borderRadius:12,background:C.white,border:`1px solid ${C.brd}`,fontSize:12,fontWeight:600,color:C.text,boxShadow:"0 1px 4px rgba(0,0,0,0.04)",cursor:"pointer"}}>Show less ▴</div></div>}
  <div style={{height:1,background:C.brd,margin:"24px 0"}}/>
  {(()=>{const uncatTxns=activeTxnList.filter((t:any)=>t.unaccounted);const uncatCount=uncatTxns.length;const uncatAmt=uncatTxns.reduce((s:number,t:any)=>s+t.amt,0);return uncatCount>0?<div style={{display:"flex",alignItems:"center",gap:14,padding:"20px",background:C.white,borderRadius:16,boxShadow:"0 2px 16px rgba(0,0,0,0.04)"}}><div style={{width:44,height:44,borderRadius:12,background:"#fef3c7",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><HelpCircle size={20} strokeWidth={1.5} color="#d97706"/></div><div style={{flex:1}}><div style={{fontSize:14,fontWeight:700,color:C.text}}>{uncatCount} uncategorised spend{uncatCount>1?"s":""}</div><div style={{fontSize:12,color:C.sub,marginTop:3}}>Worth ₹{f(uncatAmt)} — help us sort them</div></div><div onClick={()=>goTxns("Unaccounted")} style={{padding:"8px 16px",borderRadius:10,background:C.blue,cursor:"pointer"}}><span style={{fontSize:12,fontWeight:600,color:"#fff"}}>Fix</span></div></div>:null;})()}
  </div><InfoBS/></div></div><div style={{position:"absolute",bottom:0,left:0,right:0,display:"flex",justifyContent:"center",padding:"12px 0 5vw",pointerEvents:"none"}}><div style={{pointerEvents:"auto"}}><NavBar/></div></div><TxnSheet/><ActSheet/><CatBS/><FilterSheet/><GmailNudgePopup/><GmailNudgeSheet/><RetroOverlay/><VoiceFlowOverlay/><Toast/></div>);
}
