import { describe, expect, it } from "vitest";
import { buildIndexContext } from "./buildIndexContext";

const group = (name: string) =>
  new Proxy(
    {},
    {
      get: (_target, prop) => `${name}.${String(prop)}`,
    },
  );

const makeContext = () =>
  buildIndexContext({
    setScreen: "setScreen.fn",
    screen: "home",
    identity: group("identity"),
    bestCardsUi: group("bestCardsUi"),
    onboardingFlow: group("onboardingFlow"),
    optimizeActionsUi: group("optimizeActionsUi"),
    overlayUi: group("overlayUi"),
    calculatorRedeemUi: group("calculatorRedeemUi"),
    cardDetailUi: group("cardDetailUi"),
    transactionUi: group("transactionUi"),
    buildingFlow: group("buildingFlow"),
    gmailFlow: group("gmailFlow"),
    nudgeVoiceFlow: group("nudgeVoiceFlow"),
  });

const LEGACY_CONTEXT_KEYS = [
  "toast",
  "setToast",
  "infoSheet",
  "setInfoSheet",
  "txnSheet",
  "setTxnSheet",
  "actSheet",
  "setActSheet",
  "setScreen",
  "redeemCard",
  "setRedeemCard",
  "redeemPts",
  "setRedeemPts",
  "redeemResult",
  "setRedeemResult",
  "redeemPref",
  "setRedeemPref",
  "redeemTab",
  "setRedeemTab",
  "howExpanded",
  "setHowExpanded",
  "openCard",
  "hasGmail",
  "setHasGmail",
  "nudgePermanentlyDismissed",
  "nudgeDismissals",
  "setShowGmailNudgeSheet",
  "showGmailNudge",
  "setShowGmailNudge",
  "retroEnrichFromGmail",
  "dismissNudge",
  "setNudgePermanentlyDismissed",
  "showGmailNudgeSheet",
  "relinkingGmail",
  "showVoiceFlow",
  "setShowVoiceFlow",
  "setVoiceTranscript",
  "setVoiceMatch",
  "setIsListening",
  "recognitionRef",
  "voiceCardIndex",
  "setVoiceCardIndex",
  "isListening",
  "beginListening",
  "voiceTranscript",
  "voiceMatch",
  "confirmVoiceMatch",
  "showCardMappingUI",
  "setShowCardMappingUI",
  "mappingStep",
  "setMappingStep",
  "mappingSearchQ",
  "setMappingSearchQ",
  "showSkipConfirm",
  "setShowSkipConfirm",
  "showResolutionSummary",
  "setShowResolutionSummary",
  "capSheet",
  "setCapSheet",
  "catSheet",
  "setCatSheet",
  "catStep",
  "setCatStep",
  "selCat",
  "setSelCat",
  "setRemovedTxns",
  "removedTxns",
  "filterSheet",
  "setFilterSheet",
  "filterTab",
  "setFilterTab",
  "setFilters",
  "setSortBy",
  "sortBy",
  "filters",
  "toggleFilter",
  "multiToggle",
  "isState1",
  "isState2",
  "isState3",
  "cardMapping",
  "setCardMapping",
  "screen",
  "ci",
  "setCi",
  "actFilter",
  "setActFilter",
  "getFilteredActions",
  "selBrand",
  "setSelBrand",
  "calcAmt",
  "setCalcAmt",
  "calcPopup",
  "setCalcPopup",
  "calcResult",
  "setCalcResult",
  "searchQ",
  "setSearchQ",
  "calcTab",
  "setCalcTab",
  "calcFilter",
  "setCalcFilter",
  "optTab",
  "setOptTab",
  "optSheet",
  "setOptSheet",
  "optSheetFrom",
  "setOptSheetFrom",
  "optExpanded",
  "setOptExpanded",
  "bestCardDetail",
  "setBestCardDetail",
  "portfolioNew",
  "setPortfolioNew",
  "portfolioEntryCard",
  "setPortfolioEntryCard",
  "bcFilter",
  "setBcFilter",
  "bcSearch",
  "setBcSearch",
  "bcSearchOpen",
  "setBcSearchOpen",
  "bcDetTab",
  "setBcDetTab",
  "bcViewMode",
  "setBcViewMode",
  "bcSection",
  "setBcSection",
  "bcFavs",
  "setBcFavs",
  "bcSort",
  "setBcSort",
  "bcShowSort",
  "setBcShowSort",
  "bcListView",
  "setBcListView",
  "bcEligSheet",
  "setBcEligSheet",
  "bcFromScreen",
  "setBcFromScreen",
  "getCardDisplayName",
  "isCardMapped",
  "detailTab",
  "setDetailTab",
  "txnPage",
  "setTxnPage",
  "usageCat",
  "setUsageCat",
  "usageMode",
  "setUsageMode",
  "timePeriod",
  "setTimePeriod",
  "timePeriodOpen",
  "setTimePeriodOpen",
  "chartPage",
  "setChartPage",
  "dRef",
  "sentRef",
  "tabSticky",
  "spendTab",
  "setSpendTab",
  "showAllBrands",
  "setShowAllBrands",
  "activeTxnList",
  "filtered",
  "goTxns",
  "gmailStep",
  "setGmailStep",
  "gmailReturnTo",
  "completeGmailLink",
  "gmailFirstName",
  "setGmailFirstName",
  "gmailLastName",
  "setGmailLastName",
  "gmailDob",
  "setGmailDob",
  "hsbcDigits1",
  "setHsbcDigits1",
  "hsbcDigits2",
  "setHsbcDigits2",
  "buildPhase",
  "setBuildPhase",
  "buildSub",
  "buildCardReveal",
  "savePhase",
  "setSavePhase",
  "toolStep",
  "reminderStep",
  "finalLoad",
  "buildRef",
  "setMappingCompleted",
  "mappingCompleted",
  "setUserFlag",
  "userFlag",
  "startGmailFlow",
  "onStep",
  "setOnStep",
  "vpSlide",
  "setVpSlide",
  "phone",
  "setPhone",
  "otp",
  "setOtp",
  "otpTimer",
  "setOtpTimer",
  "smsStatus",
  "setSmsStatus",
  "welcomeTyped",
  "touchStartX",
  "txnCatOverrides",
  "setTxnCatOverride",
];

describe("buildIndexContext", () => {
  it("preserves the legacy context key contract", () => {
    expect(Object.keys(makeContext())).toEqual(LEGACY_CONTEXT_KEYS);
  });

  it("maps representative keys to their owning state groups", () => {
    expect(makeContext()).toMatchObject({
      setScreen: "setScreen.fn",
      screen: "home",
      hasGmail: "identity.hasGmail",
      txnSheet: "transactionUi.txnSheet",
      calcResult: "calculatorRedeemUi.calcResult",
      bestCardDetail: "bestCardsUi.bestCardDetail",
      detailTab: "cardDetailUi.detailTab",
      buildPhase: "buildingFlow.buildPhase",
      gmailStep: "gmailFlow.gmailStep",
      showVoiceFlow: "nudgeVoiceFlow.showVoiceFlow",
      toast: "overlayUi.toast",
      optTab: "optimizeActionsUi.optTab",
    });
  });
});
